name: Python Iris Analysis

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas seaborn matplotlib scikit-learn

    - name: Run Iris analysis script
      run: |
        python iris_analysis.py
